japan:
  data:
    medicalCaseCoefficient: 0.015
    theftServiceCost: 10000
    robberyCoefficient: 0.01
    medicalServiceCost: 12000
    insuranceCurrency: JPY
    operatingCountry: JAPAN

brazil:
  data:
    medicalCaseCoefficient: 0.03
    theftServiceCost: 300
    robberyCoefficient: 0.05
    medicalServiceCost: 800
    insuranceCurrency: ZAR
    operatingCountry: BRAZIL